# Generated by Django 5.0.6 on 2024-05-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelodging',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imagelodging',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='imagelodging',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='imageowner',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imageowner',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='imageowner',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sprice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sprice',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sprice',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
