# Generated by Django 5.0.6 on 2024-05-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='New post'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='New post', max_length=255),
        ),
    ]
