# Generated by Django 5.0.6 on 2024-05-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='title',
            field=models.CharField(default='New Lodging', max_length=255),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='locate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='area',
            field=models.CharField(max_length=100),
        ),
    ]
