# Generated by Django 5.0.6 on 2024-05-25 09:14

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0009_user_role_alter_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='description',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commentul',
            name='content',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.date(2024, 5, 25)),
        ),
    ]
