# Generated by Django 5.0.6 on 2024-06-02 16:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0012_alter_imagelodging_lodging_alter_sprice_lodging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelodging',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imageowner',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
