# Generated by Django 5.0.6 on 2024-06-10 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0013_alter_imagelodging_image_alter_imageowner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageowner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lodging.owner'),
        ),
    ]
