# Generated by Django 5.0.6 on 2024-06-11 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0015_alter_imageowner_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageowner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lodging.owner'),
        ),
    ]
