# Generated by Django 5.0.6 on 2024-06-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0017_alter_imageowner_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Owner'},
        ),
    ]
