# Generated by Django 5.0.6 on 2024-06-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0019_lodging_image_lodging_price_owner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodging',
            name='e_price',
        ),
        migrations.RemoveField(
            model_name='lodging',
            name='w_price',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='cmt',
        ),
        migrations.AddField(
            model_name='owner',
            name='id_num',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
